#!/usr/bin/env swift

import Foundation

enum GeneratorError: LocalizedError {
    case usage
    case missingValue(String)

    var errorDescription: String? {
        switch self {
        case .usage:
            return "Usage: swift generate_adapters.swift <tokens.json> <swift-output> [kotlin-output]"
        case .missingValue(let path):
            return "Missing or invalid token value at \(path)"
        }
    }
}

struct TokenReader {
    let root: [String: Any]

    func number(_ path: String) throws -> Double {
        let token = try object(at: path)
        guard let value = token["$value"] as? [String: Any],
              let number = value["value"] as? NSNumber
        else { throw GeneratorError.missingValue(path) }
        return number.doubleValue
    }

    func cubicBezier(_ path: String) throws -> [Double] {
        let token = try object(at: path)
        guard let values = token["$value"] as? [NSNumber], values.count == 4 else {
            throw GeneratorError.missingValue(path)
        }
        return values.map(\.doubleValue)
    }

    private func object(at path: String) throws -> [String: Any] {
        var current: Any = root
        for component in path.split(separator: ".").map(String.init) {
            guard let object = current as? [String: Any], let next = object[component] else {
                throw GeneratorError.missingValue(path)
            }
            current = next
        }
        guard let result = current as? [String: Any] else {
            throw GeneratorError.missingValue(path)
        }
        return result
    }
}

func literal(_ value: Double) -> String {
    if value.rounded() == value { return String(format: "%.1f", value) }
    return String(format: "%.4g", value)
}

func durationLiteral(milliseconds: Double) -> String {
    String(format: "%.4g", milliseconds / 1_000)
}

let arguments = CommandLine.arguments
guard arguments.count == 3 || arguments.count == 4 else {
    throw GeneratorError.usage
}

let tokenURL = URL(fileURLWithPath: arguments[1])
let data = try Data(contentsOf: tokenURL)
guard let root = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
    throw GeneratorError.missingValue("root")
}
let tokens = TokenReader(root: root)
let curve = try tokens.cubicBezier("global.motionCurve.standard")

let swiftOutput = """
// Generated by DesignTokens/generate_adapters.swift from
// DesignTokens/newbili-theme.tokens.json. Do not edit by hand.

import CoreGraphics
import Foundation

nonisolated enum AppInterfaceTokenValues {
    static let spacingXXS: CGFloat = \(literal(try tokens.number("global.spacing.size20")))
    static let spacingXS: CGFloat = \(literal(try tokens.number("global.spacing.size40")))
    static let spacingSmall: CGFloat = \(literal(try tokens.number("global.spacing.size80")))
    static let spacingMedium: CGFloat = \(literal(try tokens.number("global.spacing.size120")))
    static let spacingLarge: CGFloat = \(literal(try tokens.number("global.spacing.size160")))
    static let spacingXLarge: CGFloat = \(literal(try tokens.number("global.spacing.size240")))

    static let controlRadius: CGFloat = \(literal(try tokens.number("global.radius.size100")))
    static let surfaceRadius: CGFloat = \(literal(try tokens.number("global.radius.size140")))
    static let overlayRadius: CGFloat = \(literal(try tokens.number("global.radius.size200")))

    static let feedbackDuration: TimeInterval = \(durationLiteral(milliseconds: try tokens.number("global.motionDuration.fast")))
    static let enterDuration: TimeInterval = \(durationLiteral(milliseconds: try tokens.number("global.motionDuration.gentle")))
    static let exitDuration: TimeInterval = \(durationLiteral(milliseconds: try tokens.number("global.motionDuration.fast")))
    static let containerDuration: TimeInterval = \(durationLiteral(milliseconds: try tokens.number("global.motionDuration.slow")))

    static let standardCurveX1 = \(literal(curve[0]))
    static let standardCurveY1 = \(literal(curve[1]))
    static let standardCurveX2 = \(literal(curve[2]))
    static let standardCurveY2 = \(literal(curve[3]))
}
""" + "\n"

let swiftOutputURL = URL(fileURLWithPath: arguments[2])
try FileManager.default.createDirectory(
    at: swiftOutputURL.deletingLastPathComponent(),
    withIntermediateDirectories: true
)
try swiftOutput.write(to: swiftOutputURL, atomically: true, encoding: .utf8)

if arguments.count == 4 {
    let kotlinOutput = """
// Generated by DesignTokens/generate_adapters.swift from newbili-theme.tokens.json.
// Map dimensions to dp at the Compose component boundary.
internal object NewbiliFluentTokens {
    const val spacingXXS = \(literal(try tokens.number("global.spacing.size20")))f
    const val spacingXS = \(literal(try tokens.number("global.spacing.size40")))f
    const val spacingSmall = \(literal(try tokens.number("global.spacing.size80")))f
    const val spacingMedium = \(literal(try tokens.number("global.spacing.size120")))f
    const val spacingLarge = \(literal(try tokens.number("global.spacing.size160")))f
    const val spacingXLarge = \(literal(try tokens.number("global.spacing.size240")))f
    const val controlRadius = \(literal(try tokens.number("global.radius.size100")))f
    const val surfaceRadius = \(literal(try tokens.number("global.radius.size140")))f
    const val overlayRadius = \(literal(try tokens.number("global.radius.size200")))f
    const val feedbackDurationMillis = \(Int(try tokens.number("global.motionDuration.fast")))
    const val enterDurationMillis = \(Int(try tokens.number("global.motionDuration.gentle")))
    const val exitDurationMillis = \(Int(try tokens.number("global.motionDuration.fast")))
    const val containerDurationMillis = \(Int(try tokens.number("global.motionDuration.slow")))
}
""" + "\n"
    let kotlinOutputURL = URL(fileURLWithPath: arguments[3])
    try FileManager.default.createDirectory(
        at: kotlinOutputURL.deletingLastPathComponent(),
        withIntermediateDirectories: true
    )
    try kotlinOutput.write(to: kotlinOutputURL, atomically: true, encoding: .utf8)
}
