// Generated by DesignTokens/generate_adapters.swift from
// DesignTokens/newbili-theme.tokens.json. Do not edit by hand.

import CoreGraphics
import Foundation

nonisolated enum AppInterfaceTokenValues {
    static let spacingXXS: CGFloat = 2.0
    static let spacingXS: CGFloat = 4.0
    static let spacingSmall: CGFloat = 8.0
    static let spacingMedium: CGFloat = 12.0
    static let spacingLarge: CGFloat = 16.0
    static let spacingXLarge: CGFloat = 24.0

    static let controlRadius: CGFloat = 10.0
    static let surfaceRadius: CGFloat = 14.0
    static let overlayRadius: CGFloat = 20.0

    static let feedbackDuration: TimeInterval = 0.15
    static let enterDuration: TimeInterval = 0.25
    static let exitDuration: TimeInterval = 0.15
    static let containerDuration: TimeInterval = 0.3

    static let standardCurveX1 = 0.33
    static let standardCurveY1 = 0.0
    static let standardCurveX2 = 0.67
    static let standardCurveY2 = 1.0
}
